# Generated by Django 5.0.3 on 2024-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0002_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
