# Generated by Django 5.0.3 on 2024-06-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_shopproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='slug',
        ),
    ]
