# Generated by Django 5.0.3 on 2024-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0004_remove_shopproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
    ]
